# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ablu/ubuntu-texlive-full:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: Config Latex env 
        run: |
          apt-get update
          apt-get update
          # 安装中文包和git控制器
          apt-get install -y git language-pack-zh-hans language-pack-zh-hant 
          # 处理字体
          mkdir -p /usr/share/fonts/opentype
          git clone https://github.com/a20185/adobefonts
          chmod +x adobefonts/runner.sh
          adobefonts/runner.sh
          # 刷新缓存以及之后的操作
          fc-cache -f -v
          # 将Times New Roman 更换为 Nimbus No9 L字体
          sed -i 's/Times New Roman/Nimbus Roman No9 L/g' sysuthesis.cls
          rm -R adobefonts
      
      - name: Compile
        run: make pdf

      - uses: actions/upload-artifact@v2
        with:
          path: main.pdf